#!/bin/bash
set -euo pipefail  # Strict error handling

# ==========================================
# Configuration Variables
# ==========================================
NAMESERVERS=(
    "8.8.8.8"       # Google Primary
    "8.8.4.4"       # Google Secondary
    "1.1.1.1"       # Cloudflare Primary
    "208.67.222.222" # OpenDNS Secondary
)

# ==========================================
# Utility Functions
# ==========================================
function info() {
    echo -e "\033[1;32m[INFO] $1\033[0m"
}

function warning() {
    echo -e "\033[1;33m[WARN] $1\033[0m"
}

function error() {
    echo -e "\033[1;31m[ERROR] $1\033[0m" >&2
    exit 1
}

# ==========================================
# Main Script
# ==========================================

# 1. Backup existing resolv.conf
info "Creating backup of /etc/resolv.conf..."
if [ -f "/etc/resolv.conf" ]; then
    sudo cp /etc/resolv.conf /etc/resolv.conf.bak.$(date +%Y%m%d_%H%M%S)
else
    warning "/etc/resolv.conf not found, skipping backup"
fi

# 2. Check if resolv.conf is managed by systemd-resolved
if systemctl is-active --quiet systemd-resolved; then
    warning "systemd-resolved is active. Consider using:"
    warning "sudo systemd-resolve --set-dns=8.8.8.8 --set-dns=8.8.4.4"
    read -p "Continue anyway? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# 3. Check if resolv.conf is a symlink
if [ -L "/etc/resolv.conf" ]; then
    info "Removing symlink /etc/resolv.conf..."
    sudo rm -f /etc/resolv.conf
fi

# 4. Create new resolv.conf
info "Creating new /etc/resolv.conf..."
{
    echo "# Generated by $(basename "$0") on $(date)"
    echo "# DO NOT EDIT MANUALLY (file is locked)"
    for ns in "${NAMESERVERS[@]}"; do
        echo "nameserver $ns"
    done
    echo "options rotate timeout:1 attempts:2"
} | sudo tee /etc/resolv.conf > /dev/null

# 5. Set permissions
sudo chmod 644 /etc/resolv.conf

# 6. Lock the file
info "Locking /etc/resolv.conf..."
if sudo chattr +i /etc/resolv.conf 2>/dev/null; then
    info "File successfully locked (immutable)"
else
    warning "Could not lock file (chattr not supported?)"
fi

# 7. Verification
info "Verifying configuration..."
echo -e "\nCurrent /etc/resolv.conf:"
cat /etc/resolv.conf

echo -e "\nDNS resolution test:"
if command -v dig &>/dev/null; then
    dig google.com +short || warning "DNS test failed"
else
    nslookup google.com || warning "DNS test failed"
fi

info "Operation completed successfully"
